### ISSUE TITLE
.ccmod outputs do not work

### ISSUE THREAD

**Issue by elluminance** [krypciak/cc-vim#1]
Your .ccmods for v1.4.0 and v1.5.0 completely lack a `plugin.js` making them completely useless. I notice that v1.3.1 seems to be functional.

![image](https://github.com/krypciak/cc-vim/assets/49847844/328aab04-1708-4580-9a19-411578bf4d57)

**Comment by krypciak** [comment]
![Screenshot_20240202-063643_Iceraven](https://github.com/krypciak/cc-vim/assets/115574014/cfe17b64-bdef-4551-859f-2e10ef3d9ea7)
welp
